[profile.default]
optimizer_runs = 1000000

[rpc_endpoints]
mainnet = "https://rpc.flashbots.net/fast"
polygon = "https://polygon.llamarpc.com"
polygon-zkevm = "https://zkevm-rpc.com"
bsc = "https://binance.llamarpc.com"
gnosis = "https://gnosis.drpc.org"
fantom = "https://rpc3.fantom.network"
okx = "https://exchainrpc.okex.org"
avalanche = "https://avalanche.drpc.org"
arbitrum = "https://arbitrum.llamarpc.com"
optimism = "https://optimism.llamarpc.com"
manta = "https://1rpc.io/manta"
moonriver = "https://rpc.api.moonriver.moonbeam.network"
moonbeam = "https://1rpc.io/glmr"
canto = "https://canto.slingshot.finance"
celo = "https://1rpc.io/celo"
fuse = "${RPC_URL_FUSE}"
cronos = "https://evm.cronos.org"
velas = "${RPC_URL_VELAS}"
harmony = "${RPC_URL_HARMONY}"
evmos = "${RPC_URL_EVMOS}"
aurora = "${RPC_URL_AURORA}"
boba = "${RPC_URL_BOBA}"
nova = "https://arbitrum-nova.publicnode.com"
zksync = "https://zksync-era.blockpi.network/v1/rpc/public"
zkevm = "https://zkevm-rpc.com"
base = "https://base.llamarpc.com"
linea = "https://linea.drpc.org"
kava = "https://evm.kava.io"
opbnb = "https://opbnb.publicnode.com"
mantle = "https://rpc.mantle.xyz"
scroll = "https://rpc.scroll.io"
pulsechain = "https://rpc.pulsechain.com"
zora = "https://rpc.zora.energy"
klaytn = "https://klaytn.blockpi.network/v1/rpc/public"
flare = "https://flare-api.flare.network/ext/C/rpc"

# testnets
goerli = "https://ethereum-goerli.publicnode.com"
sepolia = "https://1rpc.io/sepolia"
holesky = "${RPC_URL_HOLESKY}"
mumbai = "https://polygon-mumbai-bor.publicnode.com"
arbitrum-goerli = "https://arbitrum-goerli.publicnode.com"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
consensys-zkevm-testnet = "${RPC_URL_CONSENSYS_ZKEVM_TESTNET}"
berachain-artio = "https://rpc.ankr.com/berachain_testnet"
bsc-testnet = "https://bsc-testnet.publicnode.com"
scroll-alpha = "https://alpha-rpc.scroll.io/l2"
linea-goerli = "https://rpc.goerli.linea.build"
avalanche-fuji = "https://api.avax-test.network/ext/bc/C/rpc"
arbitrum-stylus-testnet = "https://stylus-testnet.arbitrum.io/rpc"
optimism-goerli = "https://optimism-goerli.publicnode.com"
optimism-sepolia = "https://rpc.ankr.com/optimism_sepolia"
fantom-testnet = "https://rpc.testnet.fantom.network"
frame-testnet = "https://rpc.testnet.frame.xyz/http"
taiko-jolnir = "https://rpc.jolnir.taiko.xyz"
mevm-m1 = "https://mevm.devnet.m1.movementlabs.xyz/v1"
mode-sepolia = "https://sepolia.mode.network"
opbnb-testnet = "https://opbnb-testnet-rpc.bnbchain.org"
mantle-testnet = "https://rpc.testnet.mantle.xyz"
base-goerli = "https://goerli.base.org"
sei-devnet = "https://evm-rpc-arctic-1.sei-apis.com"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
polygon = { key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api" }
bsc = { key = "${BSCSCAN_KEY}", url = "https://api.bscscan.com/api" }
gnosis = { key = "${GNOSISBSCOUT_KEY}", url = "https://blockscout.com/poa/xdai/api" }
fantom = { key = "${FTMSCAN_KEY}", url = "https://api.ftmscan.com/api" }
avalanche = { key = "${SNOWTRACE_KEY}", url = "https://api.snowtrace.io/api" }
arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
optimism = { key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api" }
moonriver = { key = "${MOONRIVER_MOONSCAN_KEY}", url = "https://api-moonriver.moonscan.io/api" }
moonbeam = { key = "${MOONBEAM_MOONSCAN_KEY}", url = "https://api-moonbeam.moonscan.io/api" }
nova = { key = "${NOVA_ARBISCAN_KEY}", url = "https://nova.arbiscan.io/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
linea = { key = "${LINEASCAN_API_KEY}", url = "https://api.lineascan.build/api" }

#testnets
linea-goerli = { key = "${LINEASCAN_API_KEY}", url = "https://api-goerli.lineascan.build/api" }
goerli = { key = "${ETHERSCAN_KEY}" }
sepolia = { key = "${ETHERSCAN_KEY}" }
mumbai = { key = "${POLYGONSCAN_KEY}", url = "https://api-testnet.polygonscan.com/api" }
arbitrum-goerli = { key = "${ARBISCAN_KEY}", url = "https://api-goerli.arbiscan.io/api" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
